In [10]:
import pandas as pd
from typing import Any, Dict

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)


positive = {"tangible harm definitively occurred",
            "imminent risk of tangible harm (near miss) did occur",
            "non-imminent risk of tangible harm (an issue) occurred"}
negative = {"no tangible harm, near-miss, or issue",
            "unclear"}

def compute_coincidence_rate_grouped(df, pos=positive, neg=negative, output_table=False):
    matches = (
        (df['gen_Tangible Harm'].isin(pos) & df['orig_Tangible Harm'].isin(pos))
        | (df['gen_Tangible Harm'].isin(neg) & df['orig_Tangible Harm'].isin(neg))
    )
    rate = matches.mean() * 100
    if output_table:
        table = pd.DataFrame({
            'gen_Tangible Harm': df['gen_Tangible Harm'],
            'orig_Tangible Harm': df['orig_Tangible Harm'],
            'grouped_match': matches
        })
        return rate, table
    return rate

def compute_coincidence_rate_strict(df, output_table=False):
    """Compute exact-match coincidence percentage between generated and original labels"""
    strict_matches = df['gen_Tangible Harm'] == df['orig_Tangible Harm']
    rate = strict_matches.mean() * 100
    if output_table:
        table = pd.DataFrame({
            'gen_Tangible Harm': df['gen_Tangible Harm'],
            'orig_Tangible Harm': df['orig_Tangible Harm'],
            'strict_match': strict_matches
        })
        return rate, table
    return rate

## Compare tangible harm columns, single attrbute
Compute the percentage of entries where `gen_Tangible Harm` matches `orig_Tangible Harm`

## generating a specific attribute

In [57]:
# Process multiple datasets and display results in a table
full = [
    ('4o', './data/classifications-attribute-4o.csv'),
    ('4o - pass 2', './data/classifications-attribute-4o-2.csv'),
    ('4o - pass 3', './data/classifications-attribute-4o-3.csv'),
    ('4o - pass 4', './data/classifications-attribute-4o-4.csv'),
    ('o4-mini', './data/classifications-attribute-o4-mini.csv'),
]

results = []
for label, path in full:
    df = pd.read_csv(path)
    results.append({
        'Dataset': label,
        'Rows': len(df),
        'Grouped %': compute_coincidence_rate_grouped(df),
        'Strict %': compute_coincidence_rate_strict(df)
    })
results_df = pd.DataFrame(results)
results_df

       Dataset  Rows  Grouped %  Strict %
0           4o    20       55.0      55.0
1  4o - pass 2    20       65.0      65.0
2  4o - pass 3    20       60.0      60.0
3  4o - pass 4     4       75.0      75.0
4      o4-mini    20       90.0      85.0

## generating the full classification

In [60]:
attribute = [
    ('4o', './data/classifications-full-4o.csv'),
    ('4o - pass 2', './data/classifications-full-4o-2.csv'),
    ('4o - pass 3', './data/classifications-full-4o-3.csv'),
    ('o4-mini', './data/classifications-full-o4-mini.csv'),
]

results = []
for label, path in attribute:
    df = pd.read_csv(path)
    results.append({
        'Dataset': label,
        'Rows': len(df),
        'Grouped %': compute_coincidence_rate_grouped(df),
        'Strict %': compute_coincidence_rate_strict(df)
    })

results_df = pd.DataFrame(results)
results_df

       Dataset  Rows  Grouped %  Strict %
0           4o    20  80.000000      75.0
1  4o - pass 2    20  75.000000      75.0
2  4o - pass 3    20  80.000000      75.0
3      o4-mini    15  86.666667      80.0